// Template — copy as privy.config.generated.ts (gitignored) or run
// `node scripts/generate-privy-config.js` after exporting PRIVY_APP_ID.
// AUTO-GENERATED by scripts/generate-privy-config.js in real builds.
export const PRIVY_APP_ID = '__PRIVY_APP_ID_NOT_SET__';
export const PRIVY_PLACEHOLDER = '__PRIVY_APP_ID_NOT_SET__';
